#! /usr/bin/env bash

install() (
    echo "Installing shlib..."
    url=https://github.com/AlTavares/shlib/archive/refs/heads/main.zip
    echo "Downloading shlib from ${url}..."
    curl -L "${url}" -o shlib.zip
    echo "Unzipping shlib.zip..."
    unzip shlib.zip
    trap "rm -rf shlib.zip shlib-main" EXIT
    echo "Moving shlib files to the current directory..."
    rm -rf ./shlib || true
    mv shlib-main/shlib ./shlib
)

init() (
    echo "Initializing shlib..."
    source "./shlib/init"
    shlib init bash
    success "Installation finished"
)

install && init
